; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit INA3221 Library@^1.0.1
	milesburton/DallasTemperature@^4.0.5
	paulstoffregen/OneWire@^2.3.8

; WLAN-SSID und Passwort aus Umgebungsvariablen holen:
;  -> WIFI_SSID
;  -> WIFI_PASSWORD
build_flags =
  '-std=c++17'
  '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
  '-DWIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'

board_build.embed_txtfiles =
  src/style.css
  src/script.js

; Für clangd / LSP:
; compile_commands.json erzeugen mit:
;   pio run -t compiledb